logging:
  level:
    ROOT: INFO
    ai.flowx.quickstart.connector: INFO
    io.netty: INFO
    reactor.netty: INFO
    jdk.event.security: INFO

server:
  port: 8080

spring:
  application:
    name: card management
  jackson:
    serialization:
      write_dates_as_timestamps: false
      fail-on-empty-beans: false

application:
  jaeger:
    enabled: false
    prefix: connector

management:
  health:
    kafka.enabled: true

card-management-api:
  baseUrl: https://dev-legacy-card.outmost.ro
  endpoint: /cards

spring.config.import: application-management.yml, application-kafka.yml
---
spring.config.activate.on-profile: dev

logging.level.ROOT: DEBUG
logging.level.ai.flowx.quickstart.connector: DEBUG